--UN CLIENTE COMPRA UN VEHICULO
CREATE DATABASE EmpresaCompraVehiculo;

USE EmpresaCompraVehiculo;

CREATE TABLE EMPRESA(
NOM_EMPRESA     VARCHAR(30),
ID_EMPRESA      VARCHAR(30) PRIMARY KEY,
NUM_EMPRESA     INTEGER,
UBICACION       VARCHAR(30),
TIPO_DE_EMPRESA VARCHAR(30)
);
INSERT INTO EMPRESA(NOM_EMPRESA,ID_EMPRESA,NUM_EMPRESA,UBICACION,TIPO_DE_EMPRESA)
VALUES     ('TRANS CONDOR','TRC-134242',78677743,'C/SAVEDRA-AV/SAN PABLO','EMPRESA DE TRANSPORTES');
SELECT * FROM EMPRESA

CREATE TABLE EMPRESA_VENDEDORA(
NOM_EMP_VEN  VARCHAR(30),
ID_EMP_VEN   VARCHAR(30) PRIMARY KEY,
VENDEDOR     VARCHAR(25),
TELEFONO     INTEGER
);

INSERT INTO EMPRESA_VENDEDORA(NOM_EMP_VEN,ID_EMP_VEN,VENDEDOR,TELEFONO)
VALUES      ('IMCRUZ','IM-132098','STANLY ADREES',65557545);

SELECT * FROM EMPRESA_VENDEDORA;

CREATE TABLE VEHICULO(
COD_VEHICULO      VARCHAR(30) PRIMARY KEY,
VEHICULO          VARCHAR(30),
Nro_DE_VEHICULOS  VARCHAR(30),
MARCA             VARCHAR(30),
GARANTIA          VARCHAR(30),
PRECIO            INTEGER,
TIPO_DE_VEH       VARCHAR(30),

);
ALTER TABLE VEHICULO ALTER COLUMN Nro_DE_VEHICULOS INTEGER;

INSERT INTO VEHICULO(VEHICULO,COD_VEHICULO,Nro_DE_VEHICULOS,MARCA,GARANTIA,PRECIO,TIPO_DE_VEH)
VALUES      ('HINO','HN-S-300',5,'TOYOTA','2 AÑOS',20000,'DE TRANSPORTE');

SELECT * FROM VEHICULO;

CREATE TABLE DETALLE_COMPRA(
VENDEDOR         VARCHAR(30),--EMPRESA_VENDEDORA
COD_FACTURA      VARCHAR(30) PRIMARY KEY,--DETALLE_COMPRA
ID_EMPRESA       VARCHAR(30),--EMPRESA
ID_EMP_VEN       VARCHAR(30),--EMPRESA
Nro_DE_VEHICULOS VARCHAR(30),--VEHICULO
PRECIO           INTEGER,    --VEHICULO
GARANTIA         VARCHAR(30),--VEHICULO
NUM_EMPRESA      INTEGER,    --EMPRESA
COD_VEHICULO     VARCHAR(30) --VEHICULO

FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA),
FOREIGN KEY (ID_EMP_VEN) REFERENCES EMPRESA_VENDEDORA(ID_EMP_VEN),
FOREIGN KEY (COD_VEHICULO) REFERENCES VEHICULO(COD_VEHICULO)
);

INSERT INTO DETALLE_COMPRA(VENDEDOR,COD_FACTURA,ID_EMPRESA,ID_EMP_VEN,Nro_DE_VEHICULOS,PRECIO,GARANTIA,NUM_EMPRESA,COD_VEHICULO)
VALUES ('STANLY ADREES','PROD-231238','TRC-134242','IM-132098',5,100000,'2  AÑOS',78677743,'HN-S-300');
SELECT * FROM DETALLE_COMPRA;