--crear una base de datos con el nombre Hito2Tarea
CREATE DATABASE Hito2Tarea;
USE Hito2Tarea;
--crear la tabla universidad en la base de datos creada
CREATE TABLE universidad(

NOMBRE_UNI  VARCHAR(30),
TIPO_DE_UNI VARCHAR(30),
SEDE        VARCHAR(30),
RECTOR      VARCHAR(30),
CARRERAS    VARCHAR(30),
ESTUDIANTE  VARCHAR(30),
CREDENCIAL  VARCHAR(30) PRIMARY KEY

);
ALTER TABLE universidad ADD 
GESTION INTEGER;

ALTER TABLE universidad DROP COLUMN CARRERAS;

ALTER TABLE universidad ADD 
CARRERA VARCHAR(30);

SELECT * FROM universidad;

INSERT INTO universidad (NOMBRE_UNI,TIPO_DE_UNI,
SEDE,RECTOR,CARRERA,ESTUDIANTE,CREDENCIAL,GESTION) 
values('UNIFRANZ','PRIVADA','EL ALTO','Arq. Verónica Agreda de Pazos','ING DE SISTEMAS','JHONATAN ALANOCA','SIS13640865',2022);
INSERT INTO universidad (NOMBRE_UNI,TIPO_DE_UNI,
SEDE,RECTOR,CARRERA,ESTUDIANTE,CREDENCIAL,GESTION) 
values('UMSA','PUBLICA','LA PAZ','Oscar Arnaldo Heredia Vargas','INFORMATICA','JOSE TORREZ','IF12324312',2019);
INSERT INTO universidad (NOMBRE_UNI,TIPO_DE_UNI,
SEDE,RECTOR,CARRERA,ESTUDIANTE,CREDENCIAL,GESTION) 
values('UPEA','PUBLICA','EL ALTO','Dr. Carlos Condori Titirico','MEDICINA','ANDRES LOPEZ','MED12321213',2018);
INSERT INTO universidad (NOMBRE_UNI,TIPO_DE_UNI,
SEDE,RECTOR,CARRERA,ESTUDIANTE,CREDENCIAL,GESTION) 
values('UNIVALLE','PRIVADA','LA PAZ','ng. Gonzalo Ruiz Ostria','BIOMEDICINA','KEVIN QUISPE','BIO12638376',2021);

SELECT * FROM universidad;






