
CREATE DATABASE PREGUNTAS;
USE PREGUNTAS;

CREATE TABLE estudiante(

NOMBRE  VARCHAR(30),
APELLIDO VARCHAR(30),
CREDENCIAL  VARCHAR(30) PRIMARY KEY
);
INSERT INTO estudiante(NOMBRE,APELLIDO,CREDENCIAL) 
values('DAVID','ALANOCA','SIS13640865');
INSERT INTO estudiante(NOMBRE,APELLIDO,CREDENCIAL) 
values('JHONNY','TORREZ','SIS98765432');
INSERT INTO estudiante(NOMBRE,APELLIDO,CREDENCIAL) 
values('CARLOS','CASTILLO','SIS12387623');
SELECT * FROM estudiante;

drop table;