
CREATE DATABASE POLLOS_COPA;
USE POLLOS_COPA;

CREATE TABLE cliente (

ID_CLIENTE VARCHAR(30) PRIMARY KEY,
NOMBRE     VARCHAR(30),
APELLIDO   VARCHAR(30),
EDAD       INTEGER,
DOMICILIO  VARCHAR(30)
);
CREATE TABLE pedido (

ID_PEDIDO VARCHAR(30) PRIMARY KEY,
ARTICULO  VARCHAR(30),
COSTO     INTEGER,
FECHA     VARCHAR(30)
);
CREATE TABLE detalle_pedido (

ID_DETALLE_PEDIDO VARCHAR(30) PRIMARY KEY,
ID_CLIENTE        VARCHAR(30),
ID_PEDIDO         VARCHAR(30)

FOREIGN KEY (ID_CLIENTE) REFERENCES cliente(ID_CLIENTE),
FOREIGN KEY (ID_PEDIDO) REFERENCES pedido(ID_PEDIDO),
);
INSERT INTO cliente (ID_CLIENTE,NOMBRE,APELLIDO,EDAD,DOMICILIO)
values('ER-1242132','JHOAN','TORREZ',25,'CALLE CARRASCO/Nro1231');
INSERT INTO cliente (ID_CLIENTE,NOMBRE,APELLIDO,EDAD,DOMICILIO)
values('ER-1243089','ROGER','MAMANI',15,'CALLE PASCUE/Nro3213');
SELECT * FROM cliente;

INSERT INTO pedido(ID_PEDIDO,ARTICULO,COSTO,FECHA)
values('1231141412','pizza',170,'20/8/2022');
INSERT INTO pedido(ID_PEDIDO,ARTICULO,COSTO,FECHA)
values('1423432134','ramen',50,'21/8/2022');
SELECT * FROM pedido;

INSERT INTO detalle_pedido (ID_DETALLE_PEDIDO,ID_CLIENTE,ID_PEDIDO)
values('6789187642','ER-1242132','1231141412');
INSERT INTO detalle_pedido (ID_DETALLE_PEDIDO,ID_CLIENTE,ID_PEDIDO)
values('658742569','ER-1243089','1423432134');
SELECT * FROM detalle_pedido;